spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sample
    username: sample
    password: sample

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.enable_lazy_load_no_trans: true

  liquibase:
    contexts: test
